[package]
name = "market_making"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.18"
tungstenite = "0.20"
serde_json = "1.0"
url = "2.5"
futures-util = "0.3"